name: Build Qt Modufile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        host: ${{ matrix.os == 'ubuntu-latest' && 'linux' || (matrix.os == 'macos-latest' && 'mac' || 'windows') }}
        target: 'desktop'
        arch: ${{ matrix.os == 'ubuntu-latest' && 'gcc_64' || (matrix.os == 'macos-latest' && 'clang_64' || 'win64_msvc2019_64') }}
        install-deps: 'true'

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: modufile-${{ matrix.os }}
        path: |
          build/modufile
          build/Release/modufile.exe
          build/modufile.app
